version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - deploy
      - dependencies
      - ruby
    ignore:
      - dependency-name: audited
      - dependency-name: sidekiq
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - deploy
      - dependencies
      - javascript
  - package-ecosystem: bundler
    directory: "/docs"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - github_actions
