version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: simplecov
    versions:
    - ">= 0.18.a, < 0.19"
  - dependency-name: simplecov
    versions:
    - ">= 0.19.a, < 0.20"
  - dependency-name: simplecov
    versions:
    - ">= 0.20.a, < 0.21"
  - dependency-name: govuk_design_system_formbuilder
    versions:
    - 2.4.0
  - dependency-name: parallel_tests
    versions:
    - 3.5.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
