default: &default
  ASSETS_PRECOMPILE: true
  RAILS_SERVE_STATIC_FILES: true
  RAILS_MAX_THREADS: 50
  RAILS_ENV: review
  RACK_ENV: review

review:
  <<: *default

qa:
  <<: *default
  RAILS_ENV: qa
  RACK_ENV: qa

staging:
  <<: *default
  RAILS_ENV: staging
  RACK_ENV: staging

sandbox:
  <<: *default
  RAILS_ENV: sandbox
  RACK_ENV: sandbox

production:
  <<: *default
  RAILS_ENV: production
  RACK_ENV: production
