default: &default
  ASSETS_PRECOMPILE: true
  RAILS_SERVE_STATIC_FILES: true
  RAILS_MAX_THREADS: 50
  RAILS_ENV: review_aks
  RACK_ENV: review_aks

review:
  <<: *default

qa:
  <<: *default
  RAILS_ENV: qa_aks
  RACK_ENV: qa_aks
