default: &default
  ASSETS_PRECOMPILE: true
  RAILS_SERVE_STATIC_FILES: true
  RAILS_MAX_THREADS: 50
  RAILS_ENV: review_aks
  RACK_ENV: review_aks

review:
  <<: *default

qa:
  <<: *default
  RAILS_ENV: qa_aks
  RACK_ENV: qa_aks

staging:
  <<: *default
  RAILS_ENV: staging_aks
  RACK_ENV: staging_aks

sandbox:
  <<: *default
  RAILS_ENV: sandbox_aks
  RACK_ENV: sandbox_aks

production:
  <<: *default
  RAILS_ENV: production_aks
  RACK_ENV: production_aks
