# Offense count: 1
RSpec/MultipleDescribes:
  Exclude:
    - 'spec/requests/api/v3/courses/index_spec.rb'

# Offense count: 2
RSpec/OverwritingSetup:
  Exclude:
    - 'spec/requests/api/v2/providers/update_accrediting_providers_spec.rb'

# Offense count: 6
RSpec/RepeatedExample:
  Exclude:
    - 'spec/models/course_enrichment_spec.rb'
    - 'spec/serializers/api/public/v1/serializable_course_spec.rb'
    - 'spec/serializers/api/v3/serializable_course_spec.rb'

# Offense count: 6
RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/models/course_spec.rb'
    - 'spec/models/provider/validation_spec.rb'
    - 'spec/models/provider_spec.rb'

# Offense count: 2
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/controllers/api/public/v1/providers/courses_controller_spec.rb'

# Offense count: 2
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/organisation.rb'
    - 'app/models/provider.rb'

# Offense count: 1
# Configuration parameters: MinBranchesCount.
Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/with_qualifications.rb'
