require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - ./config/rubocop/layout.yml
  - ./config/rubocop/lint.yml
  - ./config/rubocop/metrics.yml
  - ./config/rubocop/naming.yml
  - ./config/rubocop/rails.yml
  - ./config/rubocop/rspec.yml
  - ./config/rubocop/style.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"

RSpec/AnyInstance:
  Enabled: false

# Remove after migration
Naming/PredicateName:
  Enabled: false

# Remove after we fix offences
Rails/I18nLocaleTexts:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'docs/lib/govuk_tech_docs/open_api/renderer.rb'

Naming/BlockForwarding:
  Exclude:
    - 'docs/lib/govuk_tech_docs/open_api/extension.rb'
