# Offense count: 2
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/controllers/api/public/v1/providers/courses_controller_spec.rb'

# Offense count: 2
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/organisation.rb'
    - 'app/models/provider.rb'

# Offense count: 1
# Configuration parameters: MinBranchesCount.
Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/with_qualifications.rb'
