plugins:
  - rubocop-factory_bot
  - rubocop-rspec_rails

inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  ParserEngine: parser_prism
  TargetRubyVersion: 3.4
