
Naming/PredicateName:
  Exclude:
    - 'app/models/course.rb'
    - 'app/models/course_enrichment.rb'
    - 'app/models/site_status.rb'
    - 'app/services/course_search_service.rb'
    - 'app/services/courses/generate_course_name_service.rb'
    - 'app/validators/phone_validator.rb'
    - 'spec/support/parse_text_table.rb'

# Offense count: 21
# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Enabled: false

# Offense count: 4
RSpec/IteratedExpectation:
  Exclude:
    - 'spec/models/concerns/courses/edit_options/qualifications_concern_spec.rb'
    - 'spec/models/course/publish_enrichments_spec.rb'
    - 'spec/requests/api/v2/organisations_spec.rb'

# Offense count: 3
RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/time_format_spec.rb'
    - 'spec/validators/phone_validator_spec.rb'
    - 'spec/validators/reference_number_format_validator_spec.rb'

# Offense count: 16
RSpec/MessageChain:
  Exclude:
    - 'spec/services/course_reporting_service_spec.rb'
    - 'spec/services/provider_reporting_service_spec.rb'
    - 'spec/services/publish_reporting_service_spec.rb'
    - 'spec/services/send_welcome_email_service_spec.rb'

# Offense count: 316
# Configuration parameters: EnforcedStyle.
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  Enabled: false

# Offense count: 1
RSpec/MultipleDescribes:
  Exclude:
    - 'spec/requests/api/v3/courses/index_spec.rb'

# Offense count: 2
RSpec/OverwritingSetup:
  Exclude:
    - 'spec/requests/api/v2/providers/update_accrediting_providers_spec.rb'

# Offense count: 14
RSpec/RepeatedDescription:
  Exclude:
    - 'spec/controllers/api/v2/providers_controller_spec.rb'
    - 'spec/mailers/course_vacancies/updated_mailer_spec.rb'
    - 'spec/models/course_spec.rb'
    - 'spec/models/provider_spec.rb'
    - 'spec/requests/api/v2/providers/sites_spec.rb'
    - 'spec/services/providers/generate_course_code_service_spec.rb'

# Offense count: 6
RSpec/RepeatedExample:
  Exclude:
    - 'spec/models/course_enrichment_spec.rb'
    - 'spec/serializers/api/public/v1/serializable_course_spec.rb'
    - 'spec/serializers/api/v3/serializable_course_spec.rb'

# Offense count: 6
RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/models/course_spec.rb'
    - 'spec/models/provider/validation_spec.rb'
    - 'spec/models/provider_spec.rb'

# Offense count: 2
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/controllers/api/public/v1/providers/courses_controller_spec.rb'

# Offense count: 2
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/organisation.rb'
    - 'app/models/provider.rb'

# Offense count: 1
# Configuration parameters: MinBranchesCount.
Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/with_qualifications.rb'
