plugins:
  - rubocop-factory_bot
  - rubocop-rspec_rails

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - '.rubocop_todo.yml'
  - 'config/rubocop/rspec.yml'
  - 'config/rubocop/naming.yml'

AllCops:
  ParserEngine: parser_prism
  TargetRubyVersion: 3.4

Rails/SaveBang:
  AllowImplicitReturn: true
