approvedGitRepositories:
  - "https://github.com/govuk-one-login/service-header"
  - "https://github.com/govuk-one-login/service-header.git"
  - "https://github.com/DFE-Digital/dfe-autocomplete"
  - "https://github.com/DFE-Digital/dfe-autocomplete.git"

enableScripts: true

nodeLinker: node-modules
