approvedGitRepositories:
  - "https://github.com/govuk-one-login/service-header"
  - "https://github.com/DFE-Digital/dfe-autocomplete"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0
