name: smoke-test
description: runs smoke tests

inputs:
  environment:
    description: Environment to run tests in
    required: true
  pr-number:
    description: PR number if testing a review app
    required: false
  teams-webhook:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Smoke Tests ${{ inputs.environment }}
      shell: bash
      run: RAILS_ENV=${{ inputs.environment }} ./bin/bundle exec rspec spec/smoke --format documentation
      env:
        APP_NAME_SUFFIX: review-${{ inputs.pr-number }}

    - name: Notify teams channel on job failure
      if: ${{ failure() && inputs.environment != 'review' }}
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ inputs.teams-webhook }}
        title: Smoke tests failure
        service: Publish teacher training
        message: |
          Smoke tests failure on ${{ inputs.environment }}
