name: smoke-test
description: runs smoke tests

inputs:
  environment:
    description: Environment to run tests in
    required: true
  pr-number:
    description: PR number if testing a review app
    required: false
  slack-webhook:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Smoke Tests ${{ inputs.environment }}
      shell: bash
      run: RAILS_ENV=${{ inputs.environment }} ./bin/bundle exec rspec spec/smoke --format documentation
      env:
        APP_NAME_SUFFIX: review-${{ inputs.pr-number }}

    - name: "Notify Slack channel on failure"
      if: ${{ failure() && inputs.environment != 'review' }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_COLOR: "#ef5343"
        SLACK_ICON_EMOJI: ":github-logo:"
        SLACK_USERNAME: Publish Teacher Training
        SLACK_TITLE: Smoke tests failure
        SLACK_MESSAGE: ":alert: <!channel> Smoke tests failure on ${{ inputs.environment }} :sadparrot:"
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
