# rubocop:disable Metrics/BlockLength
name "mark_providers_as_scitts"
summary "Mark SCITT providers as scitt in the program type"

run do |opts, _args, _cmd|
  MCB.init_rails(opts)

  scitts = [
    "2Schools Consortium",
    "AA Teamworks West Yorkshire SCITT",
    "Alliance for Learning SCITT",
    "Altius Alliance",
    "Anton Andover Alliance",
    "Ashton on Mersey School SCITT",
    "Associated Merseyside Partnership SCITT",
    "Astra SCITT",
    "Barr Beacon SCITT",
    "Billericay Educational Consortium",
    "Bishop's Stortford SCITT",
    "Bournemouth Poole & Dorset Teacher Training Partnership",
    "Bourton Meadow Initial Teacher Training Centre",
    "Bradford Birth to 19 SCITT",
    "Bradford College",
    "Bromley Schoolsâ Collegiate",
    "Buckingham Partnership",
    "Cabot Learning Federation SCITT",
    "Carmel Teacher Training Partnership (CTTP)",
    "Central England Teacher Training",
    "Chepping View Primary Academy SCITT",
    "Cheshire East SCITT",
    "Chiltern Training Group",
    "Compton SCITT",
    "Cornwall School Centred Initial Teacher Training. (Cornwall SCITT)",
    "Cumbria Primary Teacher Training",
    "Devon Primary SCITT",
    "Doncaster ITT Partnership",
    "Durham SCITT",
    "East Midlands Teacher Training Partnership",
    "East of England Teacher Training",
    "East Sussex Teacher Training Partnership",
    "Educate Teacher Training",
    "Endeavour Learning SCITT",
    "e-Qualitas",
    "Essex and Thames Primary SCITT",
    "Essex Primary SCITT",
    "Essex Teacher Training",
    "Exceed SCITT",
    "Fareham and Gosport Primary SCITT",
    "Forest Independent Primary Collegiate SCITT",
    "Fylde Coast Teaching School SCITT",
    "Gateshead Primary SCITT",
    "George Abbot SCITT",
    "George Spencer Academy SCITT",
    "GLF Schools' Teacher Training",
    "Gloucestershire Initial Teacher Education Partnership (GITEP)",
    "GORSE SCITT",
    "Hamwic SCITT",
    "HART of Yorkshire",
    "Haybridge Alliance SCITT",
    "Henry Maynard Training E17",
    "High Force Education SCITT",
    "Hillingdon SCITT",
    "Huddersfield Horizon SCITT",
    "Hull SCITT",
    "i2i Teaching Partnership",
    "Inspiration Teacher Training",
    "Inspiring Leaders - Teacher Training",
    "Jewish Teacher Training Partnership",
    "Keele and North Staffordshire Teacher Education",
    "Kent and Medway Training",
    "King Edwardâs Consortium",
    "Kirklees and Calderdale SCITT",
    "Lampton LWA SCITT",
    "Landau Forte College Derby SCITT",
    "Leeds SCITT",
    "Leicester & Leicestershire SCITT",
    "Leicestershire Secondary SCITT",
    "Lincolnshire Teaching School Alliance SCITT",
    "Manchester Nexus SCITT",
    "Mersey Boroughs ITT Partnership",
    "Mid Essex Initial Teacher Training",
    "Mid Somerset Consortium for Teacher Training",
    "NELTA (North East London Teaching Alliance)",
    "Norfolk Teacher Training Centre",
    "North East Partnership SCITT (Physical Education)",
    "North Essex Teacher Training (NETT)",
    "North Lincolnshire SCITT Partnership",
    "North Manchester ITT Partnership",
    "North Tyneside SCITT",
    "North West SHARES SCITT",
    "North Wiltshire SCITT",
    "Northampton Teacher Training Partnership",
    "Northern Lights SCITT",
    "Nottinghamshire Torch SCITT",
    "Partnership London SCITT (PLS)",
    "Pennine Lancashire SCITT",
    "Poole SCITT",
    "Portsmouth Primary SCITT",
    "Prestolee SCITT",
    "Primary Catholic Partnership SCITT",
    "Prince Henry's High School & South Worcestershire SCITT",
    "Red Kite Teacher Training",
    "Redcar and Cleveland Teacher Training Partnership",
    "Ripley TSA SCITT",
    "Royal Academy of Dance",
    "Sacred Heart Newcastle SCITT",
    "SAF Initial Teacher Training",
    "SCITT in East London Schools (SCITTELS)",
    "Shotton Hall SCITT",
    "Somerset SCITT Consortium",
    "South Birmingham SCITT",
    "South Coast SCITT",
    "South West Teacher Training",
    "St. George's Academy Partnership",
    "St. Joseph's College Stoke Secondary Partnership",
    "Star Teachers SCITT",
    "Stockton-on-Tees Teacher Training Partnership",
    "Stourport SCITT",
    "Suffolk and Norfolk Primary SCITT",
    "Sutton Park SCITT",
    "Sutton SCITT",
    "Teach East",
    "Teach Kent & Sussex",
    "Teach SouthEast",
    "Thamesmead SCITT",
    "The Basingstoke Alliance SCITT",
    "The Bedfordshire Schoolsâ Training Partnership",
    "The Cambridge Partnership",
    "The Deepings SCITT",
    "The Grand Union Training Partnership",
    "The Hampshire LEARN SCITT Partnership",
    "The Havering Teacher Training Partnership",
    "The John Taylor SCITT",
    "The Learning Institute South West",
    "The National Mathematics and Physics SCITT",
    "The National Modern Languages SCITT",
    "The OAKS (Ormiston and Keele SCITT)",
    "The Pimlico-London SCITT",
    "The Sheffield SCITT",
    "The Shire Foundation",
    "The Solent SCITT",
    "The South Downs SCITT",
    "The Tommy Flowers SCITT Milton Keynes",
    "Three Counties Alliance SCITT",
    "Titan Partnership Ltd",
    "TKAT SCITT",
    "Tudor Grange SCITT",
    "Two Mile Ash ITT Partnership",
    "Wandsworth Primary Schoolsâ Consortium",
    "Wessex Schools Training Partnership",
    "West Midlands Consortium",
    "Wildern Partnership",
    "Yorkshire and Humber Teacher Training",
    "Yorkshire Wolds Teacher Training",
  ]

  time = Benchmark.measure do
    RecruitmentCycle.all.each do |cycle|
      puts "Updating SCITTS for #{cycle.year}"
      cycle.providers.where(provider_name: scitts).each do |provider|
        puts "Updating #{provider}"
        provider.provider_type = "scitt"
        provider.save!
      end
    end
  end

  puts "Time taken: %0.3f seconds" % time.real
end
# rubocop:enable Metrics/BlockLength
