# https://docs.rubocop.org/rubocop-factory_bot/cops_factorybot.html

FactoryBot/CreateList:
  Enabled: false
FactoryBot/AssociationStyle:
  Enabled: false
FactoryBot/ExcessiveCreateList:
  Enabled: false
FactoryBot/FactoryAssociationWithStrategy:
  Exclude:
    - 'spec/factories/access_requests.rb'
    - 'spec/factories/course_enrichments.rb'
    - 'spec/factories/course_enrichments.rb'
    - 'spec/factories/site_statuses.rb'