Layout/LineLength:
  Enabled: false

# Disable these cops because they do not allow reasonable code like splitting
# `attr_reader :bla, :foo` over 2 lines.

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
