# https://docs.rubocop.org/rubocop/cops_lint.html

# NOTE: Cop Rails/LexicallyScopedActionFilter conflicts with Lint/UselessMethodDefinition
# https://github.com/rubocop/rubocop-rails/issues/343
Lint/UselessMethodDefinition:
  Exclude:
    - 'app/controllers/publish/courses/applications_open_controller.rb'
    - 'app/controllers/publish/courses/modern_languages_controller.rb'
    - 'app/controllers/publish/courses/outcome_controller.rb'
    - 'app/controllers/publish/courses/sites_controller.rb'
    - 'app/controllers/publish/courses/subjects_controller.rb'
