Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/support/slack_notifications.rb'
    - 'spec/system/support_interface/daily_report_spec.rb'
    - 'spec/requests/vendor_api/api_authentication_spec.rb'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# NOTE: Cop Rails/LexicallyScopedActionFilter conflicts with Lint/UselessMethodDefinition
# https://github.com/rubocop/rubocop-rails/issues/343
Lint/UselessMethodDefinition:
  Exclude:
    - 'app/controllers/publish/courses/applications_open_controller.rb'
    - 'app/controllers/publish/courses/modern_languages_controller.rb'
    - 'app/controllers/publish/courses/outcome_controller.rb'
    - 'app/controllers/publish/courses/sites_controller.rb'
    - 'app/controllers/publish/courses/subjects_controller.rb'
