# https://docs.rubocop.org/rubocop-rails/cops.html

require: rubocop-rails

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/models/course.rb'
    - 'app/models/provider.rb'
    - 'lib/tasks/migrate_user_organisation_to_user_permission.rake'

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20190222063449_add_opted_in_to_provider.rb'
    - 'db/migrate/20190812153252_add_is_send_to_course.rb'
    - 'db/migrate/20191101115140_add_admin_to_users.rb'
    - 'db/migrate/20200227105316_add_user_notifications_table.rb'
    - 'db/migrate/20200312143851_add_course_create_to_user_notification.rb'
    - 'db/migrate/20200930155031_add_permission_given_to_contacts.rb'
    - 'db/migrate/20210527145331_add_visa_columns_to_the_database.rb'
    - 'db/migrate/20210527145331_add_visa_columns_to_the_database.rb'
    - 'db/migrate/20210609081246_add_structured_degree_columns_to_the_course_table.rb'
    - 'db/migrate/20210614130500_add_structured_gcse_columns_to_course_table.rb'
    - 'db/migrate/20210623150714_remove_structured_gcse_columns_from_course_table.rb'
    - 'db/migrate/20210623150714_remove_structured_gcse_columns_from_course_table.rb'
    - 'db/migrate/20220825093437_add_visa_fields_to_course.rb'
    - 'db/migrate/20240619150526_add_a_level_requirements_to_course.rb'
    - 'db/migrate/20240626110024_add_accept_pending_a_level_to_courses.rb'
    - 'db/migrate/20240626152030_add_accept_a_level_equivalency_to_course.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/provider.rb'
    - 'app/models/organisation.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20230905103742_delete_access_request_table.rb'

Rails/OutputSafety:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production_aks
    - development
    - test
    - sandbox

Rails/FindEach:
  Exclude:
    - 'app/services/subjects/financial_incentive_creator_service.rb'
    - 'db/migrate/20190815091422_set_application_end_dates_on_recruitment_cycles.rb'
    - 'db/migrate/20190909105439_provider_enrichment_user_not_null.rb'
    - 'db/migrate/20190913125905_migrate_subjects.rb'
    - 'db/migrate/20191016144506_copy_latest_provider_enrichment_data_to_provider.rb'
    - 'db/migrate/20190711074433_change_course_accrediting_provider_id_to_code.rb'
    - 'db/migrate/20190806102256_add_applications_open_from_to_courses.rb'
    - 'lib/tasks/correct_subject_positions.rake'


Rails/RedundantActiveRecordAllMethod:
  Exclude:
    - 'spec/services/support/data_exports/data_export_spec.rb'
    - 'spec/services/support/data_exports/data_export_spec.rb'
    - 'spec/support/feature_helpers/govuk_components.rb'

Rails/Output:
  Exclude:
    - config/initializers/console.rb

Rails/ApplicationRecord:
  Exclude:
    - config/initializers/blazer.rb

