require: rubocop-rails

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/models/course.rb'
    - 'app/models/provider.rb'
    - 'app/services/subjects/financial_incentive_set_subject_knowledge_enhancement_course_available_service.rb'
    - 'lib/tasks/migrate_user_organisation_to_user_permission.rake'

Rails/OutputSafety:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/AfterCommitOverride:
  Enabled: true

Rails/FindById:
  Enabled: false

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - sandbox
    - research
