require: rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - 'spec/controllers/concerns/error_handlers_base_spec.rb'
    - 'spec/models/site_status_spec.rb'

RSpec/LeadingSubject:
  Exclude:
    - 'spec/validators/words_count_validator_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/view_objects/notifications_view_spec.rb'
    - 'spec/support/matchers/method_to_delegate_to_service.rb'
    - 'spec/services/send_welcome_email_service_spec.rb'
    - 'spec/services/record_first_login_service_spec.rb'
    - 'spec/services/providers/copy_to_recruitment_cycle_service_spec.rb'
    - 'spec/services/notification_service/course_withdrawn_spec.rb'
    - 'spec/services/notification_service/course_vacancies_updated_spec.rb'
    - 'spec/services/notification_service/course_updated_spec.rb'
    - 'spec/services/notification_service/course_subjects_updated_spec.rb'
    - 'spec/services/notification_service/course_published_spec.rb'
    - 'spec/services/courses/copy_to_provider_service_spec.rb'
    - 'spec/services/courses/copy_to_provider_service_spec.rb'
    - 'spec/services/courses/assignable_subject_service_spec.rb'
    - 'spec/services/courses/assignable_master_subjects_service_spec.rb'
    - 'spec/services/course_serializers_service_spec.rb'
    - 'spec/policies/user_notification_preferences_policy_spec.rb'
    - 'spec/models/course_spec.rb'
    - 'spec/lib/find_constraint_spec.rb'
    - 'spec/lib/big_query/request_event_spec.rb'
    - 'spec/helpers/vacancy_helper_spec.rb'
    - 'spec/forms/support/user_form_spec.rb'
    - 'spec/forms/publish/course_funding_form_spec.rb'
    - 'spec/controllers/api/public/v1/subject_areas_controller_spec.rb'
    - 'spec/components/paginator_spec.rb'
    - 'spec/components/gcse_row_content_spec.rb'
    - 'spec/services/notification_service/course_sites_updated_spec.rb'

RSpec/StubbedMock:
  Exclude:
    - 'spec/services/publish_reporting_service_spec.rb'
    - 'spec/services/provider_reporting_service_spec.rb'
    - 'spec/services/notification_service/course_withdrawn_spec.rb'
    - 'spec/services/notification_service/course_vacancies_updated_spec.rb'
    - 'spec/services/notification_service/course_vacancies_updated_spec.rb'
    - 'spec/services/notification_service/course_updated_spec.rb'
    - 'spec/services/notification_service/course_updated_spec.rb'
    - 'spec/services/notification_service/course_subjects_updated_spec.rb'
    - 'spec/services/notification_service/course_sites_updated_spec.rb'
    - 'spec/services/notification_service/course_published_spec.rb'
    - 'spec/services/course_search_service_spec.rb'
    - 'spec/services/course_reporting_service_spec.rb'
    - 'spec/controllers/api/public/v1/providers/courses_controller_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/services/courses/generate_course_name_service_spec.rb'
    - 'spec/validators/unique_course_validator_spec.rb'
    - 'spec/services/vacancy_status_determination_service_spec.rb'
    - 'spec/services/user_associations_service/delete_spec.rb'
    - 'spec/services/user_associations_service/create_spec.rb'
    - 'spec/services/token/decode_service_spec.rb'
    - 'spec/services/support/filters/filter_spec.rb'
    - 'spec/services/rollover_service_spec.rb'
    - 'spec/services/providers/copy_to_recruitment_cycle_service_spec.rb'
    - 'spec/services/courses/assign_program_type_service_spec.rb'
    - 'spec/services/course_search_service_spec.rb'
    - 'spec/services/access_request_approval_service_spec.rb'
    - 'spec/services/authentication_service_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/models/user_notification_preferences_spec.rb'
    - 'spec/models/site_status_spec.rb'
    - 'spec/models/site_spec.rb'
    - 'spec/models/required_qualifications_summary_spec.rb'
    - 'spec/models/required_qualifications_summary_spec.rb'
    - 'spec/models/recruitment_cycle_spec.rb'
    - 'spec/models/provider_spec.rb'
    - 'spec/models/provider/validation_spec.rb'
    - 'spec/models/provider/accredited_bodies_spec.rb'
    - 'spec/models/course_spec.rb'
    - 'spec/models/course_enrichment_spec.rb'
    - 'spec/models/course/update_valid_spec.rb'
    - 'spec/models/course/update_valid_spec.rb'
    - 'spec/models/course/publishable_spec.rb'
    - 'spec/models/course/assign_program_type_spec.rb'
    - 'spec/models/contact_spec.rb'
    - 'spec/helpers/vacancy_helper_spec.rb'
    - 'spec/helpers/find/subject_helper_spec.rb'
    - 'spec/forms/publish/course_funding_form_spec.rb'
    - 'spec/features/publish/managing_users_spec.rb'
    - 'spec/features/find/search/viewing_a_course_spec.rb'
    - 'spec/features/find/search/viewing_a_course_spec.rb'
    - 'spec/decorators/course_decorator_spec.rb'
    - 'spec/controllers/api/public/v1/subject_areas_controller_spec.rb'
    - 'spec/controllers/api/public/v1/providers_controller_spec.rb'
    - 'spec/controllers/api/public/v1/providers/locations_controller_spec.rb'
    - 'spec/controllers/api/public/v1/providers/courses/locations_controller_spec.rb'
    - 'spec/controllers/api/public/v1/courses_controller_spec.rb'
    - 'spec/components/paginator_spec.rb'
    - 'spec/components/find/courses/financial_support/scholarship_and_bursary_component/view_spec.rb'
    - 'spec/controllers/api/public/v1/providers/courses_controller_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/with_stubbed_stdout.rb'
    - 'spec/support/stubbed_publish_constraint.rb'
    - 'spec/support/stubbed_find_constraint.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/docs/subjects_spec.rb'
    - 'spec/docs/subject_areas_spec.rb'
    - 'spec/docs/providers_spec.rb'
    - 'spec/docs/providers/locations_spec.rb'
    - 'spec/docs/providers/courses_spec.rb'
    - 'spec/docs/providers/courses/locations_spec.rb'
    - 'spec/docs/provider_suggestions_spec.rb'
    - 'spec/docs/courses_spec.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/services/support/filters/filter_spec.rb'
    - 'spec/services/subjects/populate_subject_areas_service_spec.rb'
    - 'spec/services/stores_user_store_spec.rb'
    - 'spec/services/providers/generate_unique_course_code_spec.rb'
    - 'spec/services/courses/assignable_master_subjects_service_spec.rb'
    - 'spec/services/course_store_spec.rb'
    - 'spec/models/provider/validation_spec.rb'
    - 'spec/models/provider/accredited_bodies_spec.rb'
    - 'spec/models/course/withdraw_spec.rb'
    - 'spec/models/course/update_valid_spec.rb'
    - 'spec/models/course/publishable_spec.rb'
    - 'spec/models/course/publish_sites_spec.rb'
    - 'spec/models/course/publish_enrichments_spec.rb'
    - 'spec/models/course/is_fee_based_spec.rb'
    - 'spec/models/course/funding_type_spec.rb'
    - 'spec/models/course/created_at_since_spec.rb'
    - 'spec/models/course/changed_at_since_spec.rb'
    - 'spec/models/course/assign_program_type_spec.rb'
    - 'spec/models/concerns/courses/edit_options_spec.rb'
    - 'spec/models/concerns/courses/edit_options/qualifications_concern_spec.rb'
    - 'spec/features/publish/courses/editing_course_length_and_funding_type.rb'
    - 'spec/controllers/concerns/error_handlers_base_spec.rb'
    - 'spec/services/user_store_spec.rb'

RSpec/MessageChain:
  Exclude:
    - 'spec/services/course_reporting_service_spec.rb'
    - 'spec/services/provider_reporting_service_spec.rb'
    - 'spec/services/publish_reporting_service_spec.rb'
    - 'spec/services/send_welcome_email_service_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/time_format_spec.rb'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/services/providers/generate_course_code_service_spec.rb'
    - 'spec/models/provider_spec.rb'
    - 'spec/models/course_spec.rb'
    - 'spec/mailers/course_vacancies/updated_mailer_spec.rb'

# In acceptance tests it's often handy to user instance variables to keep track of state
RSpec/InstanceVariable:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - "scenario"
    - "feature"

