require: rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

# In acceptance tests it's often handy to user instance variables to keep track of state
RSpec/InstanceVariable:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - "scenario"
    - "feature"

