Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

