# https://docs.rubocop.org/rubocop/cops_style.html

Style/Documentation:
  Enabled: false
Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/with_qualifications.rb'
Style/ReturnNilInPredicateMethodDefinition:
  Exclude:
    - 'app/forms/publish/notification_form.rb'

# Exclude Rails generated files
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - config/boot.rb
    - config/application.rb
    - config/environment.rb
    - config/environments/*
    - config/initializers/assets.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - bin/rails
    - bin/rake

Style/SafeNavigationChainLength:
  Enabled: true
  Exclude:
    - app/controllers/publish/courses/gcse_requirements_controller.rb
    - app/forms/publish/course_study_mode_form.rb
    - app/models/course.rb
    - app/models/course_enrichment.rb
    - app/services/courses/content_status_service.rb
    - app/services/courses/creation_service.rb
    - app/views/publish/shared/_error_wrapper.html.erb

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - spec/support/system_test_config.rb
