Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template
  Exclude:
    - app/helpers/geocode_helper.rb

Style/Alias:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatString:
  Exclude:
    - app/helpers/geocode_helper.rb

Style/AccessorGrouping:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

