# https://docs.rubocop.org/rubocop/cops_style.html

Style/Documentation:
  Enabled: false
Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/with_qualifications.rb'
Style/ReturnNilInPredicateMethodDefinition:
  Exclude:
    - 'app/forms/publish/notification_form.rb'

# Exclude Rails generated files
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - config/boot.rb
    - config/application.rb
    - config/environment.rb
    - config/environments/*
    - config/initializers/assets.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - bin/rails
    - bin/rake
