shared:
  authentication:
    - id
    - provider
    - subject_key
    - authenticable_id
    - authenticable_type
    - created_at
    - updated_at
  candidate:
    - id
    - email_address
    - created_at
    - updated_at
  saved_course:
    - id
    - candidate_id
    - course_id
    - created_at
    - updated_at
  session:
    - id
    - user_agent
    - ip_address
    - session_key
    - sessionable_id
    - sessionable_type
    - created_at
    - updated_at
  contact:
    - id
    - provider_id
    - type
    - created_at
    - updated_at
    - permission_given
  course:
    - id
    - course_code
    - name
    - profpost_flag
    - program_type
    - qualification
    - start_date
    - study_mode
    - provider_id
    - modular
    - english
    - maths
    - science
    - created_at
    - updated_at
    - changed_at
    - accredited_provider_code
    - discarded_at
    - age_range_in_years
    - applications_open_from
    - is_send
    - level
    - uuid
    - degree_grade
    - additional_degree_subject_requirements
    - degree_subject_requirements
    - accept_pending_gcse
    - accept_gcse_equivalency
    - accept_english_gcse_equivalency
    - accept_maths_gcse_equivalency
    - accept_science_gcse_equivalency
    - additional_gcse_equivalencies
    - can_sponsor_skilled_worker_visa
    - can_sponsor_student_visa
    - application_status
    - a_level_subject_requirements
    - accept_pending_a_level
    - accept_a_level_equivalency
    - additional_a_level_equivalencies
    - degree_type
    - funding
    - visa_sponsorship_application_deadline_at
  course_site:
    - id
    - course_id
    - publish
    - site_id
    - status
    - vac_status
  data_hub_process_summary:
    - id
    - type
    - status
    - started_at
    - finished_at
    - short_summary
    - created_at
    - updated_at
  study_site_placement:
    - id
    - course_id
    - site_id
    - created_at
    - updated_at
  course_subject:
    - id
    - course_id
    - subject_id
    - created_at
    - updated_at
    - position
  course_enrichment:
    - id
    - course_id
    - created_at
    - created_by_user_id
    - json_data
    - last_published_timestamp_utc
    - status
    - version
    - updated_at
    - updated_by_user_id
  feedback:
    - id
    - ease_of_use
    - experience
    - created_at
    - updated_at
  financial_incentive:
    - id
    - subject_id
    - bursary_amount
    - early_career_payments
    - scholarship
    - created_at
    - updated_at
    - subject_knowledge_enhancement_course_available
  gias_school:
    - id
    - urn
    - name
    - type_code
    - group_code
    - status_code
    - phase_code
    - minimum_age
    - maximum_age
    - ukprn
    - address1
    - address2
    - address3
    - town
    - county
    - postcode
    - website
    - telephone
    - latitude
    - longitude
    - created_at
    - updated_at
  provider_partnership:
    - id
    - accredited_provider_id
    - training_provider_id
    - created_at
    - updated_at
  provider:
    - accredited
    - selectable_school
    - show_school
    - id
    - address4
    - provider_name
    - year_code
    - provider_code
    - provider_type
    - postcode
    - website
    - address1
    - address2
    - region_code
    - created_at
    - updated_at
    - changed_at
    - recruitment_cycle_id
    - discarded_at
    - train_with_us
    - train_with_disability
    - latitude
    - longitude
    - ukprn
    - urn
    - can_sponsor_skilled_worker_visa
    - can_sponsor_student_visa
    - synonyms
    - accredited_provider_number
    - town
    - address3
  recruitment_cycle:
    - id
    - year
    - application_start_date
    - application_end_date
    - available_in_publish_from
    - available_for_support_users_from
    - created_at
    - updated_at
  site:
    - id
    - address2
    - address4
    - code
    - location_name
    - postcode
    - address1
    - provider_id
    - region_code
    - created_at
    - updated_at
    - latitude
    - longitude
    - urn
    - town
    - address3
    - site_type
    - discarded_via_script
    - added_via
  statistic:
    - id
    - json_data
    - created_at
    - updated_at
  subject:
    - id
    - type
    - subject_code
    - subject_name
    - subject_group_id
  subject_group:
    - id
    - name
    - created_at
    - updated_at
  subject_area:
    - typename
    - name
    - created_at
    - updated_at
  user:
    - id
    - sign_in_user_id
    - first_login_date_utc
    - last_login_date_utc
    - welcome_email_date_utc
    - invite_date_utc
    - accept_terms_date_utc
    - state
    - admin
    - discarded_at
    - magic_link_token_sent_at
  user_notification:
    - id
    - user_id
    - provider_code
    - course_update
    - created_at
    - updated_at
    - course_publish
  user_permission:
    - id
    - user_id
    - provider_id
    - created_at
    - updated_at
