name: deploy_v2
description: deploys application to AKS

inputs:
  arm-access-key:
    required: true
  azure-credentials:
    required: true
  environment:
    description: Environment to deploy to
    required: true
  pr-number:
    description: PR number for the review app
    required: false
  sha:
    description: Commit sha to be deployed
    required: true
  slack-webhook:
    required: true

outputs:
  deploy-url:
    value: ${{ steps.set_env_var.outputs.deploy_url }}

runs:
  using: composite
  steps:
    - name: Set Environment variables
      id: set_env_var
      shell: bash
      run: |
        tf_vars_file=terraform/aks/workspace_variables/${{ inputs.environment }}.tfvars.json
        echo "cluster=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV
        echo "app_environment=$(jq -r '.app_environment' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_name=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_app_secret_name=$(jq -r '.key_vault_app_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_infra_secret_name=$(jq -r '.key_vault_infra_secret_name' ${tf_vars_file})" >> $GITHUB_ENV

        terraform_version=$(awk '/{/{f=/^terraform/;next}f' terraform/aks/providers.tf | grep -o [0-9\.]*)
        echo "TERRAFORM_VERSION=$terraform_version" >> $GITHUB_ENV

        if [ -n "${{ inputs.pr-number }}" ]; then
          APP_NAME=${{ inputs.pr-number }}
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "deploy_url=https://publish-review-${APP_NAME}.test.teacherservices.cloud" >> $GITHUB_OUTPUT
          echo "DEPLOY_REF=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          app_environment=$(jq -r '.app_environment' ${tf_vars_file})
          echo "DEPLOY_REF=${{ github.ref }}" >> $GITHUB_ENV
          hostname=$(jq -r '.additional_hostnames[0]' ${tf_vars_file})
          if [ ${app_environment} == "production" ]; then
            echo "deploy_url=https://api2.publish-teacher-training-courses.service.gov.uk" >> $GITHUB_OUTPUT
          else
            echo "deploy_url=https://${app_environment}2.api.publish-teacher-training-courses.service.gov.uk" >> $GITHUB_OUTPUT
          fi
          echo "DEPLOY_REF=${{ github.ref }}" >> $GITHUB_ENV
        fi;

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Validate Azure Key Vault secrets
      uses: DFE-Digital/github-actions/validate-key-vault-secrets@master
      with:
        KEY_VAULT: ${{ env.key_vault_name }}
        SECRETS: |
          ${{ env.key_vault_app_secret_name }}
          ${{ env.key_vault_infra_secret_name }}

    - name: Set up environment variables
      shell: bash
      run: |
        case ${{ env.cluster }} in
          test)
            echo "cluster_rg=s189t01-tsc-ts-rg" >> $GITHUB_ENV
            echo "cluster_name=s189t01-tsc-test-aks" >> $GITHUB_ENV
            ;;
          production)
            echo "cluster_rg=s189p01-tsc-pd-rg" >> $GITHUB_ENV
            echo "cluster_name=s189p01-tsc-production-aks" >> $GITHUB_ENV
            ;;
          *)
            echo "unknown cluster"
            ;;
        esac

        if [ "${{ inputs.environment }}" == "review_aks" ] && [ "${{ inputs.pr-number }}" != "" ]; then
          echo "Set the app name to include the review app PR number."
          echo "app_name=publish-review-${{ inputs.pr-number }}" >> $GITHUB_ENV
        fi

    - name: Install kubectl
      if: ${{ inputs.environment == 'review_aks' }}
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.26.1" # default is latest stable

    - name: K8 setup
      if: ${{ inputs.environment == 'review_aks' }}
      shell: bash
      run: |
        az aks get-credentials -g ${{ env.cluster_rg }} -n ${{ env.cluster_name }}
        make install-konduit

    - name: Check whether we need to setup and restore the sanitised database
      if: ${{ inputs.environment == 'review_aks' }}
      shell: bash
      run: |
        konduit_worked=false

        stats_count=$(bin/konduit.sh ${{ env.app_name }} -- psql -xAc "select count(*) from statistic" | grep "count") && konduit_worked=true || true

        if [ "$konduit_worked" = false ] || [ "$stats_count" == 'count|0' ]; then
          echo "Postgres container query failed or stats table has no records. Setup and restore sanitised database."
          echo "USE_DB_SETUP_COMMAND=true" >> $GITHUB_ENV
        else
          echo "Database already created and restored."
          echo "USE_DB_SETUP_COMMAND=false" >> $GITHUB_ENV
        fi

    - name: Terraform init, plan & apply
      shell: bash
      run: make ${{ inputs.environment }} ci deploy
      env:
        ARM_ACCESS_KEY: ${{ inputs.arm-access-key }}
        IMAGE_TAG: ${{ inputs.sha }}
        TF_VAR_azure_credentials: ${{ inputs.azure-credentials }}
        CONFIRM_PRODUCTION: yes

    - name: Restore AKS database
      if: ${{ inputs.environment == 'review_aks' && env.USE_DB_SETUP_COMMAND == 'true' }}
      uses: ./.github/actions/restore/
      with:
        azure-credentials: ${{ inputs.azure-credentials }}
        environment: ${{ inputs.environment }}
        pr-number: ${{ inputs.pr-number }}

    - name: Run Smoke Tests for ${{ inputs.environment }}
      uses: ./.github/actions/smoke-test_v2/
      with:
        environment: ${{ inputs.environment }}
        pr-number: ${{ inputs.pr-number }}
        slack-webhook: ${{ inputs.slack-webhook }}

    - name: Alert on Failure
      if: ${{ failure() && github.ref == 'refs/heads/main' }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: twd_findpub_tech
        SLACK_COLOR: '#ef5343'
        SLACK_ICON_EMOJI: ':github-logo:'
        SLACK_USERNAME: Publish Teacher Training
        SLACK_TITLE: Deploy to ${{ inputs.environment }} Failed
        SLACK_MESSAGE: ':alert: <!channel> Deployment failure on ${{ inputs.environment }} :sadparrot:'
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
