name: deploy_v2
description: deploys application

inputs:
  arm-access-key:
    required: true
  azure-credentials:
    required: true
  environment:
    description: Environment to deploy to
    required: true
  pr-number:
    description: PR number for the review app
    required: false
  sha:
    description: Commit sha to be deployed
    required: true
  slack-webhook:
    required: true

outputs:
  deploy-url:
    value: ${{ steps.set_env_var.outputs.deploy_url }}

runs:
  using: composite
  steps:
    - name: Set Environment variables
      id: set_env_var
      shell: bash
      run: |
        echo "Input environment = ${{inputs.environment}}"
        echo "Input pr-number = ${{inputs.pr-number}}"
        echo "Input sha = ${{inputs.sha}}"

        tf_vars_file=terraform/aks/workspace_variables/${{ inputs.environment }}.tfvars.json
        echo "tf_vars_file = ${tf_vars_file}"

        terraform_version=$(awk '/{/{f=/^terraform/;next}f' terraform/aks/providers.tf | grep -o [0-9\.]*)
        echo "terraform_version = ${terraform_version}"

        echo "cluster=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV
        echo "cluster = ${cluster}"

        echo "aks_app_environment=$(jq -r '.app_environment' ${tf_vars_file})" >> $GITHUB_ENV
        echo "aks_app_environment = ${aks_app_environment}"

        echo "TERRAFORM_VERSION=$terraform_version" >> $GITHUB_ENV
        echo "TERRAFORM_VERSION = ${TERRAFORM_VERSION}"

        echo "namespace=$(jq -r '.namespace' ${tf_vars_file})" >> $GITHUB_ENV
        echo "namespace = ${namespace}"

        echo "key_vault_name=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_name = ${key_vault_name}"

        echo "key_vault_app_secret_name=$(jq -r '.key_vault_app_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_app_secret_name = ${key_vault_app_secret_name}"

        echo "key_vault_infra_secret_name=$(jq -r '.key_vault_infra_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_infra_secret_name = ${key_vault_infra_secret_name}"

        if [ -n "${{ inputs.pr-number }}" ]; then
          echo "APP_NAME=${{ inputs.pr-number }}" >> $GITHUB_ENV
          echo "deploy_url=https://publish-review-${APP_NAME}.test.teacherservices.cloud" >> $GITHUB_OUTPUT
          echo "DEPLOY_REF=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          aks_app_environment=$(jq -r '.app_environment' ${tf_vars_file})
          echo "DEPLOY_REF=${{ github.ref }}" >> $GITHUB_ENV
          hostname=$(jq -r '.gov_uk_host_names[0]' ${tf_vars_file})
          if [ ${{ inputs.environment }} == "production" ]; then
            echo "deploy_url=https://api.publish-teacher-training-courses.service.gov.uk" >> $GITHUB_OUTPUT
          else
            if [[ $cluster == 'production' ]]; then
              echo "deploy_url=https://publish-${aks_app_environment}.teacherservices.cloud" >> $GITHUB_OUTPUT
            else
              echo "deploy_url=https://publish-${aks_app_environment}.${cluster}.teacherservices.cloud" >> $GITHUB_OUTPUT
            fi
          fi
          echo "DEPLOY_REF=${{ github.ref }}" >> $GITHUB_ENV
        fi;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Validate Azure Key Vault secrets
      uses: DFE-Digital/github-actions/validate-key-vault-secrets@master
      with:
        KEY_VAULT: ${{ env.key_vault_name }}
        SECRETS: |
          ${{ env.key_vault_app_secret_name }}
          ${{ env.key_vault_infra_secret_name }}

    # - name: Terraform init, plan & apply
    #   shell: bash
    #   run: make ${{ inputs.environment }} ci deploy
    #   env:
    #     ARM_ACCESS_KEY:             ${{ inputs.arm-access-key }}
    #     IMAGE_TAG:                  ${{ inputs.sha }}
    #     TF_VAR_azure_credentials:   ${{ inputs.azure-credentials }}
    #     CONFIRM_PRODUCTION:         yes

    # Get this from the cluster data terraform module
    - name: Set up environment variables
      shell: bash
      run: |
        case ${{ env.cluster }} in
          test)
            echo "cluster_rg=s189t01-tsc-ts-rg" >> $GITHUB_ENV
            echo "cluster_name=s189t01-tsc-test-aks" >> $GITHUB_ENV
            ;;
          production)
            echo "cluster_rg=s189p01-tsc-pd-rg" >> $GITHUB_ENV
            echo "cluster_name=s189p01-tsc-production-aks" >> $GITHUB_ENV
            ;;
          *)
            echo "unknown cluster"
            ;;
        esac
        echo "app_name=publish-${{ env.aks_app_environment }}-${{ inputs.pr-number }}" >> $GITHUB_ENV

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.26.1" # default is latest stable

    - name: K8 setup
      shell: bash
      run: |
        az aks get-credentials -g ${{ env.cluster_rg }} -n ${{ env.cluster_name }}
        make install-konduit

    - name: Get sanitised backup workflow run id
      if: ${{ inputs.environment }} == "review_aks"
      shell: bash
      run: |
        workflow_run_id=$(gh run list -w "Database Backup and Restore" -s completed --json databaseId --jq '.[].databaseId' -L 1)
        echo "sanitised_backup_workflow_run_id=$workflow_run_id" >> $GITHUB_ENV

    - name: Download Sanitised Backup
      if: ${{ inputs.environment }} == "review_aks"
      shell: bash
      run: |
        pwd
        ls -lstr
        gh run download $workflow_run_id
        cd backup_sanitised
        ls -lstr

    - name: Set environment variable
      if: ${{ inputs.environment }} == "review_aks"
      shell: bash
      run: echo "backup_file_name=backup_sanitised/backup_sanitised.sql" >> $GITHUB_ENV

    - name: Restore backup to aks env database
      if: ${{ inputs.environment }} == "review_aks"
      shell: bash
      run: |
        bin/konduit.sh -i ${{ env.backup_file_name }} -t 7200 ${{ env.app_name }} -- psql


    # - name: Run Smoke Tests for ${{ inputs.environment }}
    #   uses: ./.github/actions/smoke-test/
    #   with:
    #     environment: ${{ inputs.environment }}
    #     pr-number: ${{ inputs.pr-number }}
    #     slack-webhook: ${{ inputs.slack-webhook }}

    # - name: Alert on Failure
    #   if: ${{ failure() && github.ref == 'refs/heads/main' }}
    #   uses: rtCamp/action-slack-notify@master
    #   env:
    #     SLACK_CHANNEL: twd_findpub_tech
    #     SLACK_COLOR: '#ef5343'
    #     SLACK_ICON_EMOJI: ':github-logo:'
    #     SLACK_USERNAME: Publish Teacher Training
    #     SLACK_TITLE: Deploy to ${{ inputs.environment }} Failed
    #     SLACK_MESSAGE: ':alert: <!channel> Deployment failure on ${{ inputs.environment }} :sadparrot:'
    #     SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
