gcp_api_key: please_change_me
publish_api_url: https://api.publish-teacher-training-courses.service.gov.uk
publish_url: https://www.publish-teacher-training-courses.service.gov.uk
find_url: https://www.find-postgraduate-teacher-training.service.gov.uk
extra_find_url: https://find-teacher-training-courses.service.gov.uk

STATE_CHANGE_SLACK_URL: replace_me

search_ui:
  base_url: https://www.find-postgraduate-teacher-training.service.gov.uk

base_url: https://www.publish-teacher-training-courses.service.gov.uk

dfe_signin:
  issuer: https://oidc.signin.education.gov.uk
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  profile: https://profile.signin.education.gov.uk
  user_search_url: https://support.signin.education.gov.uk/users

bg_jobs:
  save_statistic:
    cron: "0 0 * * *" # daily at midnight
    class: "SaveStatisticJob"
    queue: save_statistic
  send_entity_table_checks_to_bigquery:
    cron: "30 0 * * *"  # daily at 00:30
    class: "DfE::Analytics::EntityTableCheckJob"
    queue: low_priority
skylight:
  enable: true
environment:
  label: "Beta"
  name: "beta"
render_json_errors: true

google_tag_manager:
  find_tracking_id: GTM-TP73392
  publish_tracking_id: GTM-W56GPKW

features:
  send_request_data_to_bigquery: true
  teacher_degree_apprenticeship: true
  rollover:
    # Normally a short period of time between rollover and the next cycle
    # actually starting when it would be set to false
    has_current_cycle_started?: true
    # During rollover providers should be able to edit current & next recruitment cycle courses
    can_edit_current_and_next_cycles: true

find_valid_referers:
  - https://www.find-postgraduate-teacher-training.service.gov.uk
  - https://find-teacher-training-courses.service.gov.uk
