skylight:
  enable: false

environment:
  label: "Review"
  name: "review"

publish_url: https://qa.publish-teacher-training-courses.service.gov.uk
find_url: https://find-review-4080.test.teacherservices.cloud
apply_base_url: https://qa.apply-for-teacher-training.service.gov.uk
search_ui:
  base_url: https://find-review-4080.test.teacherservices.cloud

features:
  teacher_degree_apprenticeship: true

authentication:
  secret: secret
  mode: persona

