skylight:
  enable: false

environment:
  label: "Review"
  name: "review"

publish_url: https://qa.publish-teacher-training-courses.service.gov.uk
find_url: https://qa.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://qa.apply-for-teacher-training.service.gov.uk
search_ui:
  base_url: https://qa.find-postgraduate-teacher-training.service.gov.uk

features:
  teacher_degree_apprenticeship: true
  rollover:
    # Normally a short period of time between rollover and the next cycle
    # actually starting when it would be set to false
    has_current_cycle_started?: true
    # During rollover providers should be able to edit current & next recruitment cycle courses
    can_edit_current_and_next_cycles: true


authentication:
  secret: secret
  mode: persona

