# frozen_string_literal: true

# If you do not have OpenSSL installed, change
# the following line to use "http://"
source "https://rubygems.org"

ruby "~> 3.4.10"

gem "govuk_tech_docs", "~> 6.3"

group :test do
  gem "capybara"
  gem "rspec"
end
