name: Build No Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 0'

permissions:
  packages: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/dfe-digital/publish-teacher-training
      MIDDLEMAN_IMAGE: ghcr.io/dfe-digital/publish-teacher-training-middleman

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build middleman Docker Image
        id: build-image-middleman
        uses: DFE-Digital/github-actions/build-docker-image@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: ""
          reuse-cache: false
          max-cache: false
          target: middleman
          docker-repository: ${{ env.MIDDLEMAN_IMAGE }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
#          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image
        id: build-image
        uses: DFE-Digital/github-actions/build-docker-image@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: ""
          reuse-cache: false
          max-cache: false
          docker-repository: ${{ env.DOCKER_IMAGE }}
          extra-cache-repo: ${{ env.MIDDLEMAN_IMAGE }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
