name: Restore AKS Database

on:
  schedule: # 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      overwriteThisMorningsBackup:
        description: Not currently used
        required: true
        type: boolean
        default: false

jobs:
  restore-aks:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        environment: [qa_aks,staging_aks]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore AKS database
        id: restore_aks
        uses: ./.github/actions/restore/
        with:
          azure-credentials: ${{ secrets[format('AZURE_CREDENTIALS_{0}', matrix.environment)] }}
          environment: ${{ matrix.environment }}
