name: Delete Review App

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number of review app to delete
        required: true
        type: string

jobs:
  delete-review-app:
    name: Delete Review App ${{ github.event.pull_request.number }}
    concurrency: deploy_review_${{ github.event.pull_request.number }}
    environment: review
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set PR_NUMBER
        id: config
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Set environment variables
        shell: bash
        run: |
          source global_config/review.sh
          echo "AZURE_RESOURCE_PREFIX=${AZURE_RESOURCE_PREFIX}" >> $GITHUB_ENV
          echo "CONFIG_SHORT=${CONFIG_SHORT}" >> $GITHUB_ENV
          echo "SERVICE_SHORT=${SERVICE_SHORT}" >> $GITHUB_ENV
          echo "DEPLOY_ENV=review-${PR_NUMBER}" >> $GITHUB_ENV
          echo "USE_DB_SETUP_COMMAND=false" >> $GITHUB_ENV
          echo "TF_STATE_FILE=pr-${PR_NUMBER}.tfstate" >> $GITHUB_ENV

      - name: Delete Review App
        id: delete-review-app
        uses: DFE-Digital/github-actions/delete-review-app@master
        with:
          terraform-base: "terraform/aks"
          tf-file: "providers.tf"
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          container-name: "ptt-tfstate"
          pr-number: ${{ env.PR_NUMBER }}
          resource-group-name: "${{ env.AZURE_RESOURCE_PREFIX }}-${{env.SERVICE_SHORT}}-${{ env.CONFIG_SHORT }}-rg"
          storage-account-name: "${{ env.AZURE_RESOURCE_PREFIX }}${{env.SERVICE_SHORT}}tfstate${{ env.CONFIG_SHORT }}sa"
          tf-state-file: "${{ env.TF_STATE_FILE }}"
