name: Deploy Review App
concurrency: deploy_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
        - review
      pr-number:
        description: PR number for the existing review app to deploy to
        required: false
      sha:
        description: Commit sha of an existing build image to be deployed
        required: true

jobs:
  deploy-review-app:
    name: Deployment To Review
    concurrency: deploy_review_${{ inputs.pr-number }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Start review-${{ inputs.pr-number }} Deployment
        uses: bobheadxi/deployments@v1
        id:   deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env:   review-${{ inputs.pr-number }}
          ref: ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy App to Review
        id: deploy_review
        uses: ./.github/actions/deploy/
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}
          environment: review
          pr-number: ${{ inputs.pr-number }}
          sha: ${{ inputs.sha }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          azure-storage-connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_SANITISED }}

      - name: Update review-${{ inputs.pr-number }} status
        if:   always()
        uses: bobheadxi/deployments@v1
        with:
          step:   finish
          token:  ${{ secrets.GITHUB_TOKEN }}
          env:    review-${{ inputs.pr-number }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.deploy_review.outputs.deploy-url }}
          ref: ${{ github.head_ref }}
