name: Deploy Review App
concurrency: deploy_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
        - review
      pr-number:
        description: PR number for the existing review app to deploy to
        required: true
      sha:
        description: Commit sha of an existing build image to be deployed
        required: true

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  id-token: write

jobs:
  deploy-review-app:
    name: Deployment To Review
    concurrency: deploy_review_${{ inputs.pr-number }}
    runs-on: ubuntu-latest
    environment:
      name: review
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy App to Review
        id: deploy_review
        uses: ./.github/actions/deploy/
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          environment: review
          pr-number: ${{ inputs.pr-number }}
          sha: ${{ inputs.sha }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          azure-storage-connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_SANITISED }}

      - name: Post comment to Pull Request ${{ github.event.number }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: aks
          message: |
            Review app deployed to ${{ steps.deploy_review.outputs.deploy-url }}
