name: Deploy v2
concurrency: deploy_v2_${{ github.ref_name }}

on:
  push:
    branches:
      - 238-add-aks-review-apps
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
        - review_aks
      pr-number:
        description: PR number for the review app
        required: false
      sha:
        description: Commit sha to be deployed
        required: true

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write

jobs:
  deploy-v2-review-app:
    name: Deployment To Review v2
    concurrency: deploy_v2_review_${{ github.event.pull_request.number }}
    # if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy_v2') }}
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      # - name: Start review_aks-${{ github.event.pull_request.number }} Deployment
      #   uses: bobheadxi/deployments@v1
      #   id:   deployment
      #   with:
      #     step: start
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     env:   review_aks-${{ github.event.pull_request.number }}
      #     ref: ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy App to Review v2
        id: deploy_v2_review
        uses: ./.github/actions/deploy_v2/
        with:
          arm-access-key: ${{ secrets.ARM_ACCESS_KEY_REVIEW_AKS }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS_REVIEW_AKS }}
          environment: review_aks
          pr-number: ${{ inputs.pr-number }}
  #         pr-number: ${{ github.event.pull_request.number }}
  #         sha: ${{ needs.build.outputs.image_tag }}
          sha: ${{ inputs.sha }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

  #     - name: Update review_aks-${{ github.event.pull_request.number }} status
  #       if:   always()
  #       uses: bobheadxi/deployments@v1
  #       with:
  #         step:   finish
  #         token:  ${{ secrets.GITHUB_TOKEN }}
  #         env:    review_aks-${{ github.event.pull_request.number }}
  #         status: ${{ job.status }}
  #         deployment_id: ${{ steps.deployment.outputs.deployment_id }}
  #         env_url: ${{ steps.deploy_v2_review.outputs.deploy-url }}
  #         ref: ${{ github.head_ref }}
