name: Smoke Tests v2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run tests against (review)'
        default: qa_aks
        required: true
        type: choice
        options:
        - review_aks
        - qa_aks
        - staging_aks
        - sandbox_aks
        - production_aks
      pr:
        description: 'The PR number if the environment is review'
        required: false

jobs:
  smoke_tests:
    name: smoke-tests-${{ github.event.inputs.environment }}
    concurrency: smoke-tests-${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Smoke Tests for ${{ github.event.inputs.environment }}
        uses: ./.github/actions/smoke-test_v2/
        with:
          environment: ${{ github.event.inputs.environment }}
          pr-number: ${{ github.event.inputs.pr }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
